import { 
  UserProfile, 
  Account, 
  Category, 
  Transaction, 
  Goal, 
  Budget, 
  NotificationItem, 
  AppSettings 
} from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_centra_01',
  name: 'Alex Morgan',
  email: 'alex.morgan@centra.io',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  isPro: true,
  planExpiry: '2027-12-31',
  baseCurrency: 'BDT',
  createdAt: '2025-01-15T08:00:00.000Z',
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc_checking',
    name: 'Primary Checking',
    type: 'checking',
    balance: 6420.50,
    currency: 'BDT',
    accountNumberMasked: '•••• 4829',
    bankName: 'Chase Premier',
    color: '#6C5CE7',
    cardBrand: 'visa',
    isPrimary: true,
  },
  {
    id: 'acc_savings',
    name: 'High Yield Vault',
    type: 'savings',
    balance: 18950.00,
    currency: 'BDT',
    accountNumberMasked: '•••• 8912',
    bankName: 'Ally High Yield (4.5% APY)',
    color: '#1FAE71',
    cardBrand: 'generic',
  },
  {
    id: 'acc_credit',
    name: 'Sapphire Preferred',
    type: 'credit',
    balance: -482.30,
    currency: 'BDT',
    accountNumberMasked: '•••• 6041',
    bankName: 'Chase Credit',
    color: '#FF6B57',
    cardBrand: 'mastercard',
    creditLimit: 12000,
  },
  {
    id: 'acc_euro',
    name: 'Global Euro Travel',
    type: 'checking',
    balance: 2150.00,
    currency: 'BDT',
    accountNumberMasked: '•••• 3390',
    bankName: 'Revolut Premium',
    color: '#0984E3',
    cardBrand: 'visa',
  },
  {
    id: 'acc_invest',
    name: 'Growth Portfolio',
    type: 'investment',
    balance: 14320.80,
    currency: 'BDT',
    accountNumberMasked: '•••• 7104',
    bankName: 'Vanguard Index',
    color: '#F5A524',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_dining', name: 'Food & Dining', icon: 'Utensils', color: '#FF7675', type: 'expense', budgetLimit: 800 },
  { id: 'cat_shopping', name: 'Shopping', icon: 'ShoppingBag', color: '#FD79A8', type: 'expense', budgetLimit: 500 },
  { id: 'cat_housing', name: 'Housing & Rent', icon: 'Home', color: '#6C5CE7', type: 'expense', budgetLimit: 2200 },
  { id: 'cat_transport', name: 'Transport & Fuel', icon: 'Car', color: '#0984E3', type: 'expense', budgetLimit: 300 },
  { id: 'cat_entertainment', name: 'Entertainment', icon: 'Film', color: '#A29BFE', type: 'expense', budgetLimit: 250 },
  { id: 'cat_health', name: 'Health & Wellness', icon: 'HeartPulse', color: '#00CEC9', type: 'expense', budgetLimit: 200 },
  { id: 'cat_subs', name: 'Subscriptions', icon: 'Repeat', color: '#E17055', type: 'expense', budgetLimit: 120 },
  { id: 'cat_travel', name: 'Travel & Vacation', icon: 'Plane', color: '#FDCB6E', type: 'expense', budgetLimit: 600 },
  { id: 'cat_salary', name: 'Salary & Wages', icon: 'Briefcase', color: '#1FAE71', type: 'income' },
  { id: 'cat_freelance', name: 'Freelance & Bonus', icon: 'TrendingUp', color: '#00B894', type: 'income' },
  { id: 'cat_invest_inc', name: 'Dividends & Yield', icon: 'Coins', color: '#55EFC4', type: 'income' },
  { id: 'cat_transfer', name: 'Transfer & Payment', icon: 'ArrowRightLeft', color: '#636E72', type: 'expense' },
];

const now = new Date();
const todayISO = now.toISOString().split('T')[0];
const yesterday = new Date(now);
yesterday.setDate(yesterday.getDate() - 1);
const yesterdayISO = yesterday.toISOString().split('T')[0];

const day2 = new Date(now);
day2.setDate(day2.getDate() - 2);
const day2ISO = day2.toISOString().split('T')[0];

const day3 = new Date(now);
day3.setDate(day3.getDate() - 3);
const day3ISO = day3.toISOString().split('T')[0];

const day5 = new Date(now);
day5.setDate(day5.getDate() - 5);
const day5ISO = day5.toISOString().split('T')[0];

const day7 = new Date(now);
day7.setDate(day7.getDate() - 7);
const day7ISO = day7.toISOString().split('T')[0];

const day12 = new Date(now);
day12.setDate(day12.getDate() - 12);
const day12ISO = day12.toISOString().split('T')[0];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_01',
    type: 'expense',
    amount: 14.75,
    currency: 'BDT',
    categoryId: 'cat_dining',
    categoryName: 'Food & Dining',
    categoryIcon: 'Utensils',
    categoryColor: '#FF7675',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    merchant: 'Blue Bottle Coffee',
    date: `${todayISO}T09:30:00.000Z`,
    note: 'Morning artisan pour-over with team',
    tags: ['Daily', 'Coffee'],
    isPinned: true,
    resultingBalance: 6420.50,
  },
  {
    id: 'tx_02',
    type: 'expense',
    amount: 88.50,
    currency: 'BDT',
    categoryId: 'cat_dining',
    categoryName: 'Food & Dining',
    categoryIcon: 'Utensils',
    categoryColor: '#FF7675',
    accountId: 'acc_credit',
    accountName: 'Sapphire Preferred',
    merchant: 'Trader Joe’s Market',
    date: `${todayISO}T18:15:00.000Z`,
    note: 'Weekly organic groceries & pantry restock',
    tags: ['Groceries'],
    isPinned: false,
    resultingBalance: -482.30,
  },
  {
    id: 'tx_03',
    type: 'expense',
    amount: 28.40,
    currency: 'BDT',
    categoryId: 'cat_transport',
    categoryName: 'Transport & Fuel',
    categoryIcon: 'Car',
    categoryColor: '#0984E3',
    accountId: 'acc_credit',
    accountName: 'Sapphire Preferred',
    merchant: 'Uber Ride',
    date: `${yesterdayISO}T21:40:00.000Z`,
    note: 'Downtown meeting transit',
    tags: ['Transit'],
    isPinned: false,
    resultingBalance: -393.80,
  },
  {
    id: 'tx_04',
    type: 'expense',
    amount: 19.99,
    currency: 'BDT',
    categoryId: 'cat_subs',
    categoryName: 'Subscriptions',
    categoryIcon: 'Repeat',
    categoryColor: '#E17055',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    merchant: 'Spotify Premium Family',
    date: `${yesterdayISO}T04:00:00.000Z`,
    note: 'Monthly streaming recurring subscription',
    tags: ['Recurring', 'Entertainment'],
    isRecurring: true,
    recurringInterval: 'monthly',
    isPinned: false,
    resultingBalance: 6435.25,
  },
  {
    id: 'tx_05',
    type: 'income',
    amount: 4850.00,
    currency: 'BDT',
    categoryId: 'cat_salary',
    categoryName: 'Salary & Wages',
    categoryIcon: 'Briefcase',
    categoryColor: '#1FAE71',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    merchant: 'Fintech Nexus Corp',
    date: `${day2ISO}T08:00:00.000Z`,
    note: 'Bi-weekly Direct Deposit payroll',
    tags: ['Payroll', 'Income'],
    isPinned: true,
    resultingBalance: 6455.24,
  },
  {
    id: 'tx_06',
    type: 'expense',
    amount: 129.00,
    currency: 'BDT',
    categoryId: 'cat_entertainment',
    categoryName: 'Entertainment',
    categoryIcon: 'Film',
    categoryColor: '#A29BFE',
    accountId: 'acc_credit',
    accountName: 'Sapphire Preferred',
    merchant: 'Concert Tickets (LiveNation)',
    date: `${day3ISO}T19:20:00.000Z`,
    note: 'Indie rock weekend festival passes',
    tags: ['Vacation', 'Events'],
    isPinned: false,
    resultingBalance: -365.40,
  },
  {
    id: 'tx_07',
    type: 'expense',
    amount: 64.20,
    currency: 'BDT',
    categoryId: 'cat_shopping',
    categoryName: 'Shopping',
    categoryIcon: 'ShoppingBag',
    categoryColor: '#FD79A8',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    merchant: 'Uniqlo Flagship',
    date: `${day5ISO}T14:10:00.000Z`,
    note: 'Merino wool sweater & winter basics',
    tags: ['Apparel'],
    isPinned: false,
    resultingBalance: 1605.24,
  },
  {
    id: 'tx_08',
    type: 'income',
    amount: 1200.00,
    currency: 'BDT',
    categoryId: 'cat_freelance',
    categoryName: 'Freelance & Bonus',
    categoryIcon: 'TrendingUp',
    categoryColor: '#00B894',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    merchant: 'Stripe Payout (Design Consult)',
    date: `${day7ISO}T11:00:00.000Z`,
    note: 'Mobile UX design sprint delivery',
    tags: ['SideHustle'],
    isPinned: false,
    resultingBalance: 1669.44,
  },
  {
    id: 'tx_09',
    type: 'expense',
    amount: 2100.00,
    currency: 'BDT',
    categoryId: 'cat_housing',
    categoryName: 'Housing & Rent',
    categoryIcon: 'Home',
    categoryColor: '#6C5CE7',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    merchant: 'Skyline Lofts Property',
    date: `${day12ISO}T06:00:00.000Z`,
    note: 'Monthly luxury apartment lease & parking',
    tags: ['Rent', 'Fixed'],
    isRecurring: true,
    recurringInterval: 'monthly',
    isPinned: true,
    resultingBalance: 469.44,
  },
  {
    id: 'tx_10',
    type: 'transfer',
    amount: 500.00,
    currency: 'BDT',
    categoryId: 'cat_transfer',
    categoryName: 'Transfer & Payment',
    categoryIcon: 'ArrowRightLeft',
    categoryColor: '#636E72',
    accountId: 'acc_checking',
    accountName: 'Primary Checking',
    toAccountId: 'acc_savings',
    recipient: 'High Yield Vault',
    date: `${day12ISO}T12:00:00.000Z`,
    note: 'Auto savings goal allocation (House Deposit)',
    tags: ['Savings'],
    resultingBalance: 2569.44,
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal_house',
    name: 'Dream Apartment Deposit',
    icon: 'Home',
    color: '#6C5CE7',
    targetAmount: 12000,
    currentAmount: 8400,
    startDate: '2025-06-01',
    targetDate: '2027-04-30',
    linkedAccountId: 'acc_savings',
    monthlyContribution: 450,
  },
  {
    id: 'goal_tokyo',
    name: 'Tokyo Autumn Vacation',
    icon: 'Plane',
    color: '#FF7675',
    targetAmount: 4500,
    currentAmount: 1450,
    startDate: '2025-08-01',
    targetDate: '2026-10-15',
    linkedAccountId: 'acc_euro',
    monthlyContribution: 200,
  },
  {
    id: 'goal_emergency',
    name: '6-Month Emergency Shield',
    icon: 'ShieldCheck',
    color: '#1FAE71',
    targetAmount: 20000,
    currentAmount: 18950,
    startDate: '2024-11-01',
    targetDate: '2026-12-31',
    linkedAccountId: 'acc_savings',
    monthlyContribution: 500,
  },
  {
    id: 'goal_car',
    name: 'Electric Vehicle Upgrade',
    icon: 'Car',
    color: '#0984E3',
    targetAmount: 15000,
    currentAmount: 4200,
    startDate: '2025-09-01',
    targetDate: '2027-08-31',
    linkedAccountId: 'acc_savings',
    monthlyContribution: 350,
  }
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bud_dining',
    categoryId: 'cat_dining',
    categoryName: 'Food & Dining',
    categoryIcon: 'Utensils',
    categoryColor: '#FF7675',
    limitAmount: 800,
    spentAmount: 612.40,
    alertThreshold: 80,
    period: 'monthly',
  },
  {
    id: 'bud_ent',
    categoryId: 'cat_entertainment',
    categoryName: 'Entertainment',
    categoryIcon: 'Film',
    categoryColor: '#A29BFE',
    limitAmount: 250,
    spentAmount: 285.00, // 114% over budget to test warning state!
    alertThreshold: 80,
    period: 'monthly',
  },
  {
    id: 'bud_shop',
    categoryId: 'cat_shopping',
    categoryName: 'Shopping',
    categoryIcon: 'ShoppingBag',
    categoryColor: '#FD79A8',
    limitAmount: 500,
    spentAmount: 230.50,
    alertThreshold: 80,
    period: 'monthly',
  },
  {
    id: 'bud_trans',
    categoryId: 'cat_transport',
    categoryName: 'Transport & Fuel',
    categoryIcon: 'Car',
    categoryColor: '#0984E3',
    limitAmount: 300,
    spentAmount: 140.20,
    alertThreshold: 80,
    period: 'monthly',
  },
  {
    id: 'bud_health',
    categoryId: 'cat_health',
    categoryName: 'Health & Wellness',
    categoryIcon: 'HeartPulse',
    categoryColor: '#00CEC9',
    limitAmount: 200,
    spentAmount: 85.00,
    alertThreshold: 80,
    period: 'monthly',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    type: 'budget',
    title: 'Budget Alert: Entertainment',
    message: 'You have spent $285.00 of your $250.00 budget (114% exceeded).',
    timestamp: `${todayISO}T08:15:00.000Z`,
    isRead: false,
    severity: 'alert',
  },
  {
    id: 'notif_02',
    type: 'goal',
    title: 'Goal Milestone on Track! 🚀',
    message: 'Emergency Shield is now at 94.7% of its $20,000 target.',
    timestamp: `${yesterdayISO}T16:45:00.000Z`,
    isRead: false,
    severity: 'success',
  },
  {
    id: 'notif_03',
    type: 'security',
    title: 'New Device Session Verified',
    message: 'Centra Web accessed from Chrome on macOS (San Francisco, CA).',
    timestamp: `${day2ISO}T10:02:00.000Z`,
    isRead: true,
    severity: 'info',
  },
  {
    id: 'notif_04',
    type: 'transaction',
    title: 'Direct Deposit Received',
    message: 'Tech Nexus Corp deposited $4,850.00 into Primary Checking.',
    timestamp: `${day2ISO}T08:01:00.000Z`,
    isRead: true,
    severity: 'success',
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  theme: 'light',
  baseCurrency: 'BDT',
  privacyMode: false,
  security: {
    biometricEnabled: true,
    pinLockEnabled: true,
    pinCode: '1234',
    twoFactorEnabled: true,
    twoFactorType: 'authenticator',
    twoFactorContact: '+1 (555) 392-8812',
    lastLogin: new Date().toISOString(),
  },
  notifications: {
    transactionAlerts: true,
    budgetOverruns: true,
    securityAlerts: true,
    billReminders: true,
    weeklyDigest: true,
  },
};
